# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9f4dd68aa1ff5bb6a74f18af86ff428fa8a251c5fce152b4c0f9fe95a6f0f691d581a09b6c38d8c4c4eef370d24500ac536443b1b847bb6e1190799e2d740c5

test:
  secret_key_base: 76c5dae5a066878b6c83f1eae7a338b858696e2cdccad257135f9dfbd7cd656e4d9258be168f4686e66cbab62ea675fa49f292b67437917faab61bf5941fea4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
